# Generated by Django 5.0 on 2026-02-05 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=100, verbose_name="Nom (Français)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Nom (English)"),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom scientifique"
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Catégorie")),
                (
                    "growing_season_days",
                    models.IntegerField(verbose_name="Durée de croissance (jours)"),
                ),
                (
                    "water_requirement",
                    models.CharField(max_length=50, verbose_name="Besoin en eau"),
                ),
                (
                    "temperature_min",
                    models.FloatField(verbose_name="Température min (°C)"),
                ),
                (
                    "temperature_max",
                    models.FloatField(verbose_name="Température max (°C)"),
                ),
                ("optimal_ph_min", models.FloatField(verbose_name="pH optimal min")),
                ("optimal_ph_max", models.FloatField(verbose_name="pH optimal max")),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (Français)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "ordering": ["name_fr"],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("NORTH", "Nord"),
                            ("FAR_NORTH", "Extrême-Nord"),
                            ("ADAMAWA", "Adamaoua"),
                            ("CENTER", "Centre"),
                            ("SOUTH", "Sud"),
                            ("EAST", "Est"),
                            ("WEST", "Ouest"),
                            ("LITTORAL", "Littoral"),
                            ("NORTHWEST", "Nord-Ouest"),
                            ("SOUTHWEST", "Sud-Ouest"),
                        ],
                        max_length=50,
                        verbose_name="Région",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                (
                    "area_hectares",
                    models.FloatField(verbose_name="Superficie (hectares)"),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("SANDY", "Sableux"),
                            ("CLAY", "Argileux"),
                            ("LOAM", "Limoneux"),
                            ("SILT_LOAM", "Argilo-limoneux"),
                            ("SANDY_LOAM", "Sablo-limoneux"),
                        ],
                        max_length=50,
                        verbose_name="Type de sol",
                    ),
                ),
                (
                    "soil_ph",
                    models.FloatField(blank=True, null=True, verbose_name="pH du sol"),
                ),
                (
                    "organic_matter",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Matière organique %"
                    ),
                ),
                (
                    "irrigation_available",
                    models.BooleanField(
                        default=False, verbose_name="Irrigation disponible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ferme",
                "verbose_name_plural": "Fermes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CropSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("DRY", "Saison sèche"),
                            ("RAINY", "Saison des pluies"),
                            ("TRANSITION", "Transition"),
                        ],
                        max_length=20,
                        verbose_name="Type de saison",
                    ),
                ),
                ("planting_date", models.DateField(verbose_name="Date de plantation")),
                (
                    "expected_harvest_date",
                    models.DateField(verbose_name="Date de récolte prévue"),
                ),
                (
                    "actual_harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de récolte réelle"
                    ),
                ),
                (
                    "area_planted",
                    models.FloatField(verbose_name="Superficie plantée (ha)"),
                ),
                (
                    "fertilizer_used",
                    models.BooleanField(default=False, verbose_name="Engrais utilisé"),
                ),
                (
                    "npk_amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Quantité NPK (kg/ha)"
                    ),
                ),
                (
                    "pesticide_applications",
                    models.IntegerField(
                        default=0, verbose_name="Applications pesticides"
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type d'irrigation"
                    ),
                ),
                (
                    "yield_kg_per_ha",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Rendement (kg/ha)"
                    ),
                ),
                (
                    "yield_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellente"),
                            ("GOOD", "Bonne"),
                            ("AVERAGE", "Moyenne"),
                            ("POOR", "Faible"),
                        ],
                        max_length=20,
                        verbose_name="Qualité",
                    ),
                ),
                (
                    "total_production_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Production totale (kg)"
                    ),
                ),
                (
                    "production_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Coût de production",
                    ),
                ),
                (
                    "market_price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix de marché (FCFA/kg)",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Revenu total",
                    ),
                ),
                (
                    "profit_margin",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Marge bénéficiaire %"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="core.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saison de culture",
                "verbose_name_plural": "Saisons de culture",
                "ordering": ["-planting_date"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=50, verbose_name="Région")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix (FCFA/kg)"
                    ),
                ),
                (
                    "supply_level",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Niveau d'offre"
                    ),
                ),
                (
                    "demand_level",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Niveau de demande"
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="core.crop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prix de marché",
                "verbose_name_plural": "Prix de marché",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("CROP_RECOMMENDATION", "Recommandation de culture"),
                            ("YIELD_FORECAST", "Prévision de rendement"),
                            ("DISEASE_RISK", "Risque de maladie"),
                            ("MARKET_PRICE", "Prix de marché"),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="Données d'entrée")),
                ("output_data", models.JSONField(verbose_name="Résultats")),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Score de confiance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="core.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédiction",
                "verbose_name_plural": "Prédictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        max_length=5,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Clair"), ("dark", "Sombre")],
                        default="light",
                        max_length=10,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "notification_email",
                    models.BooleanField(
                        default=True, verbose_name="Notifications email"
                    ),
                ),
                (
                    "notification_sms",
                    models.BooleanField(
                        default=False, verbose_name="Notifications SMS"
                    ),
                ),
                (
                    "default_farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.farm",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence utilisateur",
                "verbose_name_plural": "Préférences utilisateur",
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "temperature_max",
                    models.FloatField(verbose_name="Température max (°C)"),
                ),
                (
                    "temperature_min",
                    models.FloatField(verbose_name="Température min (°C)"),
                ),
                (
                    "temperature_avg",
                    models.FloatField(verbose_name="Température moy (°C)"),
                ),
                ("rainfall_mm", models.FloatField(verbose_name="Précipitations (mm)")),
                ("humidity_percent", models.FloatField(verbose_name="Humidité (%)")),
                (
                    "wind_speed_kmh",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Vitesse du vent (km/h)"
                    ),
                ),
                (
                    "solar_radiation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Radiation solaire (W/m²)"
                    ),
                ),
                (
                    "evapotranspiration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Évapotranspiration (mm)"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données météo",
                "verbose_name_plural": "Données météo",
                "ordering": ["-date"],
                "unique_together": {("farm", "date")},
            },
        ),
    ]
